account_id = "d5b568a800b5583bd423f1628d9dc009"
name = "todolist"
type = "webpack"
route = ""
workers_dev = true
zone_id = ""
compatibility_date = "2022-11-14"

[site]
bucket = "./build"
entry-point = "workers-site"